#[cfg(test)]
mod test {
    use std::collections::HashMap;

    #[test]
    #[should_panic]
    fn invalid_http_get() {
        panic!(blindfold::http_get("www.notarealsite/foo/bar"));
    }

    #[test]
    fn file_map() {
        let mut map: HashMap<String, String> = HashMap::new(); 
        map.insert(String::from("rust"),
                    String::from("https://raw.githubusercontent.com/toptal/gitignore/master/templates/Rust.gitignore"));
        let langs = vec!["rust"];
        assert_eq!(blindfold::generate_gitignore_file(langs, &map), "# RUST gitignore generated by Blindfold\n\n# Generated by Cargo\n# will have compiled files and executables\n/target/\n\n# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries\n# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html\nCargo.lock\n\n# These are backup files generated by rustfmt\n**/*.rs.bk\n\n\n");
    }

    //fn serializing_the_response() {
        // test an invalid json with serde
        // test valid json 
        //
        // test the creation of the filemap
        // are all other files correctly ignored?
    //}

    //fn creating_the_file() {
        // test the title maker function with another language (maybe chinese to demonstrate uni
        // code)
        // 
    //}

    //fn interface() {
       // test the similarity function
       // make sure it always gives a suggestion even with random characters
       // test with numbers
       // test with only one letter difference
       // make sure if a suggestion is denied, that nothing for it is included in the gitignore
    //}

}
